//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agl.Tests.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Agl.Tests.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;name&quot;: &quot;Bob&quot;,
        ///    &quot;gender&quot;: &quot;Male&quot;,
        ///    &quot;age&quot;: 23,
        ///    &quot;pets&quot;: [
        ///      {
        ///        &quot;name&quot;: &quot;Garfield&quot;,
        ///        &quot;type&quot;: &quot;Cat&quot;
        ///      },
        ///      {
        ///        &quot;name&quot;: &quot;Fido&quot;,
        ///        &quot;type&quot;: &quot;Dog&quot;
        ///      }
        ///    ]
        ///  },
        ///	{
        ///		&quot;name&quot;: &quot;Jennifer&quot;,
        ///		&quot;gender&quot;: &quot;Female&quot;,
        ///		&quot;age&quot;: 18,
        ///		&quot;pets&quot;: [
        ///			{
        ///				&quot;name&quot;: &quot;Garfield&quot;,
        ///				&quot;type&quot;: &quot;Cat&quot;
        ///			}
        ///		]
        ///	},
        ///	{
        ///		&quot;name&quot;: &quot;Steve&quot;,
        ///		&quot;gender&quot;: &quot;Male&quot;,
        ///		&quot;age&quot;: 45,
        ///		&quot;pets&quot;: null
        ///	},
        ///	{
        ///		&quot;name&quot;: &quot;Fred&quot;,
        ///		&quot;gender&quot;: &quot;Male&quot;,
        ///		&quot;age&quot;: 40,
        ///		&quot;pets&quot;: [
        ///			{
        ///				&quot;name&quot;: &quot;Tom&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string people {
            get {
                return ResourceManager.GetString("people", resourceCulture);
            }
        }
    }
}
